<?php
namespace ArtInvest\UserBundle\Entity;
/**
* AppleRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}